name: Bug report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "needs triage"]
type: bug
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to file a bug. Please include as much detail as possible.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the minimal steps to reproduce.
      placeholder: "1.\n2.\n3."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you thought would happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Screenshots or logs
      description: Add any helpful output (stack traces, logs, screenshots). Redact secrets.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version or commit
      description: Tag, release, or commit SHA.
  - type: input
    id: os
    attributes:
      label: OS and version
      description: e.g., Ubuntu 24.04, macOS 15, Windows 11.
  - type: input
    id: python
    attributes:
      label: Python version
      description: e.g., 3.13.1.
  - type: input
    id: install
    attributes:
      label: Installation method
      description: e.g., uv, pip, container image.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help.
  - type: markdown
    attributes:
      value: >-
        If this could be a security issue, please follow the process in SECURITY.md instead of filing a public issue.
