name: Feature request
description: Suggest an idea or improvement
title: "[Feature] "
labels: ["enhancement", "needs triage"]
assignees: []
type: feature
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for proposing an improvement. Please describe the problem and the solution you have in mind.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A concise description of the feature or change you want.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Problem statement
      description: What problem does this solve? Who benefits?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work? Include API/CLI examples if relevant.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options you looked at and why they are less suitable.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, prior art, or any other details (including code samples) that would help us evaluate this request.
